>P1;5HAF
structureX:5HAF: 1: : 338: : : : :
MGSSHHHHHHSSGLEVLFQGPVSDEALTLLFSAVENGDQNCIDLLCNLALRNDDLGHRVEKFLFDLFSGKRTGSSDIDKKINQACLVLHQIANNDITKDNTEWKKLHAPSRLLYMAGSATTDLSKKIGIAHKIMGDQFAQTDQEQVGVENLWCGARMLSSDELAAATQGLVQESPLLSVNYPIGLIHPTTKENILSTQLLEKIAQSGLSHNEVFLVNTGDHWLLCLFYKLAEKIKCLIFNTYYDLNENTKQEIIEAAKIAGISESDEVNFIEMNLQNNVPNGCGLFCYHTIQLLSNAGQNDPATTLREFAENFLTLSVEEQALFNTQTRRQIYEYSLQ*
>P1;5ubw
 : : : : : : : : :
PLGSRMLSSDELAAATQGLVQESPLLSVNYPIGLIHPTTKENILSTQLLEKIAQSGLSHNEVFLVNTGDHWLLCLFYKLAEKIKCLIFNTYYDLNENTKQEIIEAAKIAGISESDEVNFIEMNLQNNVPNGCGLFCYHTIQLLSNAGQNDPATTLREFAENFLTLSVEEQALFNTQTRRQIYEYSLQ-------------------------------------------------------------------------------------------------------------------------------------------------------*
